[package]
name = "erlang_rt"
version = "0.1.0"
authors = ["Dmytro Lytovchenko"]


[features]
default = ["r20", "dev_build"]
r20 = []
# Enabling dev build adds functions to print internal structures
dev_build = []


[dependencies]
bytes = "0.4.5"
num = "0.1.40"
bit_field = "0.7.0"
compress = "0.1.2"
lazy_static = "0.2"
clippy = {version = "*", optional = true}

rt_defs = { path = "lib/rt_defs" }


[profile.release]
lto = true
panic = 'abort'
