[package]
name = "erlang_rt"
version = "0.1.0"
authors = ["Dmytro Lytovchenko"]
edition = "2018"

[features]
default = ["r20", "dev_build"]
r20 = []
# Enabling dev build adds functions to print internal structures
dev_build = []


[dependencies]
bit_field = "0.7.0"
bytes = "0.4.5"
clippy = {version = "*", optional = true}
compress = "0.1.2"
lazy_static = "0.2"
num = "0.1.40"
#log = "0.4.0"


[profile.release]
lto = true
panic = 'abort'
