[package]
name = "erlang_rt"
version = "0.1.0"
authors = ["Dmytro Lytovchenko"]

[features]
default = ["r20"]
r20 = []

[dependencies]
bytes = "0.4.5"
num = "0.1.40"

[profile.release]
lto = true
panic = 'abort'
